apiVersion: v1
kind: ConfigMap
metadata:
  name: annapolis-config
data:
  zk.host: zookeeper.default.svc.cluster.local
  zk.port: "2181"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: annapolis-deployment
  labels:
    app: annapolis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: annapolis
  template:
    metadata:
      labels:
        app: annapolis
    spec:
      containers:
        - name: annapolis
          image: annapolis:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: ZK_HOST
              valueFrom:
                configMapKeyRef:
                  name: annapolis-config
                  key: zk.host
            - name: ZK_PORT
              valueFrom:
                configMapKeyRef:
                  name: annapolis-config
                  key: zk.port
---
apiVersion: v1
kind: Service
metadata:
  name: annapolis-service
spec:
  selector:
    app: annapolis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
